### ISSUE TITLE
Removing the melee auto-hit

### ISSUE THREAD

**Issue by olifog** [Tvde1/TF2-Scripts#6]
Hello! This is a wonderful config, I've been using it for quite some time- but there are just a couple things I'd like to change. It's hard for me to find them in all the files, so I was wondering if you could help!
I'd like to remove the auto-attack when you switch to slot3. I use melee alot with hitting anything (atomizer etc.) and this is pretty irritating. Also, I don't know if this is a bug, but after swapping to melee and back again, my primary continuously fires as well. I have to fix this by pressing m1...
Thanks so much! All I need to know is what to change. :)

**Comment by Tvde1** [comment]
See [these](https://github.com/Tvde1/TF2-Scripts/blob/master/cfg/allclasses.cfg#L136-L137) lines?

change it to these
```
alias +melee "slot3"
alias -melee ""
```

I'm not sure about the class specific files, they might also have auto hit in them.

**Comment by olifog** [comment]
Thanks so much! Works perfectly. I did the same to the scripts in scout and sniper as well.
